# Setup
title: Giammarco D'Alessandro
description: A simple, beautiful, and powerful Jekyll theme for blogs, and zavve.
url: https://giamdalessandro.github.io
avatar: /assets/imgs/avatar_kermit.jpeg
paginate: 5
permalink: pretty
cover_image: /assets/imgs/bg_daniel-romanovsky-old-city-01.jpg

# Gem
plugins:
  - jekyll-remote-theme
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

remote_theme: vszhub/not-pure-poole

# Optimize Jekyll
exclude:
  - .git
  - .editorconfig
  - .jekyll-cache
  - .sass-cache
  - scripts/
  - Gemfile
  - Gemfile.lock
  - not-pure-poole.gemspec
  - README.md
  #- LICENSE.md