# Setup
title: Not Pure Poole
description: A simple, beautiful, and powerful Jekyll theme for blogs
url: https://giamdalessandro.github.io
avatar: /avatar.jpeg
paginate: 5
permalink: pretty
cover_image: /bg.jpeg

# Gem
plugins:
  - jekyll-remote-theme
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

remote_theme: vszhub/not-pure-poole

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  #- LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec