# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- .gitignore
- remote-themes/
- Gemfile
- Gemfile.lock
- .jekyll-cache
- .sass-cache

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme


# Site settings
encoding: utf-8 # Make sure the encoding is right
url: "https://giamdalessandro.github.io"  # .io
baseurl: ""
title: "My website"
description: "This is my new website"
permalink: pretty
logo: "/assets/logos/sf_emblem.png"


# Gem settings
## Pagination
paginate: 5
paginate_path: blog/page:num
#social: # jekyll-seo-tag > social overrides
#  name: David Darnes # jekyll-seo-tag > real name
#  links:  # jekyll-seo-tag > social aliases (sameAs)
#    - https://www.linkedin.com/in/daviddarnes
#    - https://github.com/daviddarnes

## Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/emblem_16x.png'
  32: '/assets/logos/emblem_32x.png'
  96: '/assets/logos/emblem_96x.png'
  120: '/assets/logos/emblem_120x.png'
  144: '/assets/logos/emblem_144x.png'
  180: '/assets/logos/emblem_180x.png'
  512: '/assets/logos/emblem_512x.png'
  1024: '/assets/logos/emblem_1024x.png'

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Blog
  url: /blog/
#- title: Elements
#  url: /elements/  
- title: Categories
  url: /categories/
- title: theme
  url: 

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Social links
social_links:   # Appears in sidebar.
  link: /about
  email: mailto:test@gmail.com
  GitHub: https://github.com/giamdalessandro
  #LinkedIn: https://www.linkedin.com/in/giammarco-d-dalessandro
  #RSS: /feed.xml

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "/assets/backgrounds/simon-stalenhag_by-burned-2560.jpg"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
